### ISSUE TITLE
Codecraft Requests - MQTT over WIFI

### ISSUE THREAD

**Issue by vongomben** [Seeed-Studio/CodeCraft#10]
I have [this code](https://github.com/vongomben/fluid-networks/blob/master/microntrollers/15_basic-MQTT/15_basic-MQTT.ino) in mind. I'd like to bring this code in CodeCraft, or something simpler

Set Wifi
### Image:

![setWifi](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/fd41a447-8eaf-4ffc-89a8-d9e6015fc055)

### Code 

```
const char ssid[] = SECRET_SSID;
const char pass[] = SECRET_PASS;

```

**Comment by vongomben** [comment]
This one is new, from scratch, because if you really drag the corresponding command from tinkergen you start don't understanding anything lol 

### Image

![setMqtt](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/f12c9055-ff35-4c82-b23e-ac4b8e321e37)

(ping me if you want the svg, I suspect you use the scratch engine to produce them though)

### Code

```
#include <MQTT.h>

#define BROKER_IP    "broker.hivemq.com"
#define DEV_NAME     "mqttdevice"
#define MQTT_USER    "mqtt_user"
#define MQTT_PW      "mqtt_password"

```

**Comment by vongomben** [comment]
We can subscribe to a new channel by creating it, a "payload" appears in the corresponding palette. 
The payload will later allow us to read and analyse the value arriving. 

![mqtt-UI-2](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/94f166d5-85c0-4f72-b37e-6ab61ef38a63)

**Comment by vongomben** [comment]
![mqtt-pub](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/651a8ab1-38c4-4d36-a8fc-a1acbbe9a06b)

Publishing on a channel affects the declaration of the publishing data

```
#include <MQTT.h>


#define MQTT_PUB     "/pubChannel"

voide setup(){

}

void loop(){

 client.publish(MQTT_PUB, data); 
}
```

**Comment by vongomben** [comment]
![mqtt-connected](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/a91763a3-b597-4c0c-a05e-38236a8efb6f)


We add to the connect() function this mqtt part to make things simpler. 
Another way could be using two different functions. 
What do you think? 

```
void connect() {
  Serial.print("checking wifi...");
  
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(1000);
  }
  Serial.print("\nconnecting...");
  
  while (!client.connect(DEV_NAME, MQTT_USER, MQTT_PW)) {
  
    Serial.print(".");
    delay(1000);

  }

  Serial.println("\nconnected!");

}

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, pass);

  client.begin(BROKER_IP, 1883, net);
  client.onMessage(messageReceived);
  
  connect();

}
```

**Comment by vongomben** [comment]
![MESSAGE-RECEIVED](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/e478460c-64ff-4568-988e-530d2e2216ad)

The messageReceived function is called whenever a message is received. We can use the payload to compare with other elements of the code. 

```
void messageReceived(String &topic, String &payload) {



}
```

  `client.subscribe(MQTT_SUB);`  has to be addedd to the `connect()` function, the `#define MQTT_SUB ` as an absolute declaration. 
```

void connect() {
  Serial.print("checking wifi...");
  
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(1000);
  }
  Serial.print("\nconnecting...");
  
  while (!client.connect(DEV_NAME, MQTT_USER, MQTT_PW)) {
  
    Serial.print(".");
    delay(1000);

  }

  Serial.println("\nconnected!");
  client.subscribe(MQTT_SUB); //SUBSCRIBE TO TOPIC /hello

}
```

I  would need a prototype to make a better example of `messageReveived()`

**Comment by chenwenhao568** [comment]
Done
