### ISSUE TITLE
Add Neopixel WS2813 

### ISSUE THREAD

**Issue by vongomben** [Seeed-Studio/CodeCraft#13]
Can you update the Chainable LED to the Neopixel Led with the official neopixel library?

**Comment by vongomben** [comment]
This Neopizel integration is a big opportunity to introduce in Codecraft for Wio terminal the pin declaration. 
My idea is that you can name more strips, on different pins, th left or right Grove connector on the Wio, ora a custom one (which should become the self defined when used with Arduino?)

![image](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/ab518b50-5dcd-46fc-a3c2-cafdd640e695)


Left stands for `BCM3`, right stands for `BCM27`

This block revolves around [this declaration](https://github.com/adafruit/Adafruit_NeoPixel/blob/master/examples/strandtest/strandtest.ino#L26):

Which basically calls: 

`#include <Adafruit_NeoPixel.h>`

and

`Adafruit_NeoPixel strip(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800); `

![Neopizel-declaration](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/5ba1e9be-8e4b-4a06-9d8b-4ed878373134)

And 
```
void setup() {

  strip.begin();           // INITIALIZE NeoPixel strip object (REQUIRED)
  strip.show();            // Turn OFF all pixels ASAP
  strip.setBrightness(50); // Set BRIGHTNESS to about 1/5 (max = 255)

}

```

**Comment by vongomben** [comment]
strip.setPixelColor(n, red, green, blue); from [here](https://learn.adafruit.com/adafruit-neopixel-uberguide/arduino-library-use)

![setPixelColor](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/cff23d7f-82c2-4c07-86ae-3611c54acd87)

**Comment by vongomben** [comment]
`strip.show`
![strip-show](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/75c28005-878d-49e5-a3ec-372ad8643cc9)

**Comment by vongomben** [comment]
`strip.clear();`

![strip-clear](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/9e3b442a-1349-4891-8c7f-f03a3ed2652c)

**Comment by vongomben** [comment]
I would add all functions in [strandtest](https://github.com/adafruit/Adafruit_NeoPixel/blob/master/examples/strandtest/strandtest.ino): ColorWipe

`colorWipe(<stripName>.Color(r,   g,   b), ms); `


![colorwipe](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/711e3766-1eac-4450-9a5a-2a959d33b200)

```
void colorWipe(uint32_t color, int wait) {
  for(int i=0; i<strip.numPixels(); i++) { // For each pixel in strip...
    strip.setPixelColor(i, color);         //  Set pixel's color (in RAM)
    strip.show();                          //  Update strip to match
    delay(wait);                           //  Pause for a moment
  }
}
```

**Comment by vongomben** [comment]
``
void colorWipe(uint32_t color, int wait) {
  for(int i=0; i<strip.numPixels(); i++) { // For each pixel in strip...
    strip.setPixelColor(i, color);         //  Set pixel's color (in RAM)
    strip.show();                          //  Update strip to match
    delay(wait);                           //  Pause for a moment
  }
}```

**Comment by baorepo** [comment]
Can you send us a PR directly? @vongomben
