### ISSUE TITLE
Add HID/USB CLIENT library to Codecraft

### ISSUE THREAD

**Issue by vongomben** [Seeed-Studio/CodeCraft#14]
It would be really cool to have the keyboard and mouse functionalities brought to Codecraft 

https://wiki.seeedstudio.com/Wio-Terminal-USBCLIENT-Keyboard/

**Comment by vongomben** [comment]
These three commands corresponds to the three different `Mouse.click`
[Link to documentation](https://www.arduino.cc/reference/en/language/functions/usb/mouse/mouseclick/)

```
#include <Mouse.h>

void setup() {

  Mouse.begin();
}

void loop() {

    Mouse.click(MOUSE_LEFT);
    Mouse.click(MOUSE_RIGHT);
    Mouse.click(MOUSE_MIDDLE);
  }
}
```


 
![MouseClick](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/b924f482-beed-4bdc-8dd5-113adcf2294e)

**Comment by vongomben** [comment]
These three commands corresponds to the three different `Mouse.press()`
The latter acts as `Mouse.release()`

![MousePressed](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/c7dbde42-d740-4e42-bf04-acedfd4cac38)

![MouseReleased](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/299df00d-7834-485f-88b9-29c007e8c4f6)


```
#include <Mouse.h>

void setup() {

  Mouse.begin();
}

void loop() {

  
    Mouse.press(MOUSE_LEFT);
    Mouse.press(MOUSE_RIGHT);
    Mouse.press(MOUSE_MIDDLE);

    Mouse.release();
  
}


```

**Comment by vongomben** [comment]
Mouse movement control 
[link to documentation](https://www.arduino.cc/reference/en/language/functions/usb/mouse/mousemove/)

`Mouse.move(xVal, yVal, wheel)`

![mousemove](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/10d8e31d-9e60-4e11-a876-b72edd84e4b1)

**Comment by vongomben** [comment]
[`Mouse.isPressed` ](Mouse.isPressed())

Reports whether a button is pressed or not. Data type: `bool`.

![mouseCondition](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/17ed60bb-18f6-4453-8e7c-236aebe922f3)

**Comment by vongomben** [comment]
Press a Specific Charaacter on the Keyboad, then release it as in [`Keyboard.write()`](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardwrite/)

![KeyboardWrite](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/96d263c7-3ed5-4f3e-a1fb-a3b135e8fea2)

```
#include <Keyboard.h>

void setup() {
 
  Keyboard.begin();
}

void loop() {

    Keyboard.write(character);
  }
}
```

**Comment by vongomben** [comment]
More Keyboard functions:

[`Keyboard.press()`](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardpress/)

`Keyboard.press(key)`

![KeyboardPress](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/362548c7-611f-4a92-99c7-6e949e7936a2)

- - - 

[`Keyboard.release()`](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardrelease/)

`Keyboard.release(key)`

![KeyboardRelease](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/eb9fa584-6c32-4537-96f5-bac5d363cc31)

- - -

[`Keyboard.releaseAll()`](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardreleaseall/)

![KeyboardReleaseAll](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/d90ab2c5-506c-4ffb-bd39-0405701490c5)

**Comment by vongomben** [comment]
Most important [`Keyboard.print()`](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardprint/) and [`Keyboard.println()`](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardprintln/) the most useful one to write as in a keyboard. 
![KeyboardPintln](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/aac210a6-52a1-425a-960c-2184bb5c1da5)

![KeyboardPrint](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/82597b3b-fc17-4cbb-be7d-ffd23df826f4)

**Comment by baorepo** [comment]
Can you send us a PR directly? @vongomben
