### ISSUE TITLE
Changelog for Codecraft 2.7.1.x

### ISSUE THREAD

**Issue by vongomben** [Seeed-Studio/CodeCraft#15]
Wonderful.
Congratulation to Seeed's team and Wen-Chen-Hao for all of this. 

If we were to make a changelog of the stuff that were added in this latest version of Codecraft:

* added wifi connectivity using [rcpWifi Library from Seeed](https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi)
* added mqtt nodes implemanting [Joel Gaehwiler Mqtt Library](https://www.arduino.cc/reference/en/libraries/mqtt/)
* added basic JSON readings/formatting  using [Arduino Json Library](https://github.com/arduino-libraries/Arduino_JSON)

I have[ this issue when parsing json](https://github.com/Seeed-Studio/CodeCraft/issues/12), but the code looks good. I don't understand, it says upload error. Will repeat tomorrow. 

I've opened several minor issues, that could make the sowftare even more solid:

- [Should the USB Client Library be ported?](https://github.com/Seeed-Studio/CodeCraft/issues/14)
- [Should be the Neopixel Library be ported?](https://github.com/Seeed-Studio/CodeCraft/issues/13)
- Should we describe the libraries we are using under the hood in a more evident way? In this way the code produced could be more portable from codecraft to other environments.  

Looking for you comments. 
I may do a little explanatory videos of this new functionalities, we could use it to revamp the platform.

**Comment by baorepo** [comment]
@vongomben  The repository is in maintenance, with no plans to add new features or fix minor bugs.

**Comment by baorepo** [comment]
https://github.com/Seeed-Studio/CodeCraft/issues/13
