### ISSUE TITLE
Upload to Arduino uno does not work from Mac

### ISSUE THREAD

**Issue by aditanase** [Seeed-Studio/CodeCraft#16]
I am trying  a simple project using original Arduino Uno + Grove Shield.
IDE Works great, but I can't upload via serial, it just hangs.

If I copy-paste the same code in the Arduino IDE it uploads and works just fine

Versions
- codecraft pc 2.7.1.5
- arduino ide 2.2.1
- macbook pro M2 max
- sonoma 14.1.1

**Comment by MatthewJeffson** [comment]
Hi Adrian! @aditanase Thank you for interesting in our software! We are actually asking for help from the community. We are happy and welcome any thoughts reported or contributions:D 
We will try to see what problem about it but excuse for our late updates. And I am using MacBook Pro M1 Pro right now which is fine. Here are my Versions:

- MacBook Pro M1 Pro
- macOS Monterey 12.6
- codecraft pc 2.7.1.5

**Comment by chenwenhao568** [comment]
<img width="721" alt="image" src="https://github.com/Seeed-Studio/CodeCraft/assets/106641814/6f9989ca-25fa-4b70-95c3-fd8b51bccbdf">
<img width="846" alt="image" src="https://github.com/Seeed-Studio/CodeCraft/assets/106641814/f8b7f0f5-8920-4b1a-9060-88d4a94ca70f">
<img width="675" alt="image" src="https://github.com/Seeed-Studio/CodeCraft/assets/106641814/9eaa515c-345b-4e52-bffd-9d08a6866b78">

Hi Adrian! @aditanase，I use Arduino Uno + Grove Shield, and the above Codecraft blocks, and it can run successfully. Except that my computer is M1, the other environment is the same as yours. If your blocks are the same as mine, then it may be a compatibility issue with M2. Can you run a setup block to test whether M2 is compatible?

**Comment by chenwenhao568** [comment]
You can refer to this link:
https://wiki.seeedstudio.com/Grove-TemperatureAndHumidity_Sensor/#play-with-codecraft

I tested the online version and the pc version, both are normal.

**Comment by baorepo** [comment]
@aditanase   Is there any update?
