### ISSUE TITLE
"export" not working under windows

### ISSUE THREAD

**Issue by vongomben** [Seeed-Studio/CodeCraft#4]
When typing `export workspace=~/CodeCraft` in powershell, we are notified that the command is not recognized. 
[Some say](https://stackoverflow.com/questions/26368306/export-is-not-recognized-as-an-internal-or-external-command) `set` is the proper one for windows.

**Comment by tianrking** [comment]
For Windows: Just enter the code below. Setting environment variables is not a necessary operation.

**Comment by chenwenhao568** [comment]
No need for docker, just execute the run script
