### ISSUE TITLE
export / pushd / workspace not working on linux

### ISSUE THREAD

**Issue by vongomben** [Seeed-Studio/CodeCraft#6]
Following the readme, when asked to `pushd workspace` we receive: `pushd: no such file or directory: workspace`

Feel free to address us to a guide is something is wrong from our side

**Comment by tianrking** [comment]
Download the code first and then set the workspace environment variable to the path where the code is downloaded.

Example:

```bash
git clone -b main https://github.com/Seeed-Projects/seeed-codecraft ~/seeed-codecraft 
export workspace=~/seeed-codecraft
```

```bash
pushd $workspace

#or

cd $workspace
```

**Comment by tianrking** [comment]
https://github.com/Seeed-Studio/CodeCraft/issues/5
