### ISSUE TITLE
Codecraft requests - JSON formatter

### ISSUE THREAD

**Issue by vongomben** [Seeed-Studio/CodeCraft#9]
We should allow the user to format the data in JSON. This will help later the sending of the data in MQTT, for example. 

We could have an extra folder called JSON, to format and send data in JSON format

**Comment by vongomben** [comment]
Let's start with the JSON format. 
We could treat the JSON encapsulation like a Variable:

![image](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/026933e8-9920-4a98-8aab-50872a40ffd6)

We can create it

![image](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/a5d26ca9-d2da-41f4-a339-372bc7ebe9ba)

Then we have the possibility to pass new parameters to it, expressing its key with a new set of commands

![image](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/89b86dc1-f400-45f8-8034-97cb8cc62b3a)

When we use the node, we invoke the [arduino_json library](https://github.com/arduino-libraries/Arduino_JSON) at the beginning of the code. 

Let's pass the light value to MyObject and call it "light"

![image](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/d30f4d53-1304-4fde-b360-c6274f0ca8d2)

This creates this code in the loop:

```
#include <Arduino_JSON.h>

void setup(){

  pinMode(WIO_LIGHT, INPUT);
}

void loop(){

 // create the JSON object 
  JSONVar MyObject;

    MyObject["light"] = (int)analogRead(WIO_LIGHT);

}
```

Whenever we use the object node in the code (i.e. in the serial port) we have the object strinfied

![image](https://github.com/Seeed-Studio/CodeCraft/assets/1215847/b2513aaa-4912-4f16-96a3-20dae2617325)

```
#include <Arduino_JSON.h>

void setup() {
  Serial.begin(9600);
  pinMode(WIO_LIGHT, INPUT);
}

void loop() {

  // create the JSON object
  JSONVar MyObject;

  MyObject["light"] = (int)analogRead(WIO_LIGHT);

  // JSON.stringify(myVar) can be used to convert the json var to a String
  String jsonString = JSON.stringify(MyObject);

  Serial.println(jsonString);

}
```

**Comment by chenwenhao568** [comment]
Done
